### ISSUE TITLE
Можно сделать переход из iframe на success url

### ISSUE THREAD

**Issue by alekssamos** [robokassa/cms-wordpress#7]
>> Важное уточнение! При работе через iFrame перенаправление покупателя на Success URL после совершения оплаты или на Fail URL при отказе от оплаты не происходит поскольку покупатель не уходит с сайта продавца, а всё время остаётся на нём.

Есть же javascript метод `top.location.href`, тогда будет перенаправлена основная страница, не фрейм.

**Comment by dmtew** [comment]
Реализовано в версии 1.8.4
